// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  scmSidebar: [{type: 'autogenerated', dirName: 'scm'}],
  mdSidebar: [{type: 'autogenerated', dirName: 'md'}],
  labSidebar: [{type: 'autogenerated', dirName: 'lab'}],
  storeSidebar: [{type: 'autogenerated', dirName: 'store'}],
};

export default sidebars;
